### ISSUE TITLE
Variable not found in Controller

### ISSUE THREAD

**Issue by wilariz** [reliv/zf2-elfinder#19]
Hello, recently I found a mistake in the IndexController, lines 93 and 94:

$fileType = $this->getEvent()->getRouteMatch()->getParam('fileType');
 if (!empty($type)) { // should by $fileType

**Comment by rodmcnew** [comment]
@wshafer want to have a look at this?

**Comment by wshafer** [comment]
@wilariz - Good catch.  I have opened PR #20  and we should have a new dot release soon.

Thanks for the report,
Westin

**Comment by wilariz** [comment]
@wshafer  You are welcome. Other think that I forgot to mention is in the README file, in the configuration block, it say to configure other mount point is with this sequence array :
'mounts' => array(
            'defaults' => array(
                'myNewMountPoint' => array (

but this never work for me, after some test I did work with this way:
'mounts' => array(
            'defaults' => array(
                'roots' => array(
                    'bookingMountPoint' => array (

Could say me if this way is ok?
Thanks.
Greetings

**Comment by rodmcnew** [comment]
@wshafer 's PR was tagged 2.0.3

**Comment by wshafer** [comment]
@wilariz - Thanks.  I'll double check against my working config and update the readme.

Thanks again for your help,
Westin
