### ISSUE TITLE
ServiceLocatorAwareInterface is deprecated error

### ISSUE THREAD

**Issue by misterpatate** [reliv/zf2-elfinder#22]
Since the 2.7 update of ZF we can't use ServiceLocator inside Controller. We must pass any dependencies with a Controller factory.
I 've proposed a solution for IndexAction but the connectorAction still buggy because of getElFinderConfig() function.
I think this function is a little too complicated to be let in a Controller.
I propose to create a Service which will be injected in the controller.

**Comment by rodmcnew** [comment]
Closing because I believe your PR fixed this

**Comment by rodmcnew** [comment]
Sorry I misunderstood. Re-opening...

**Comment by rodmcnew** [comment]
@misterpatate ,

If you want to make a PR that does what you propose, we will pull it if @wshafer approves. @wshafer is the closest to this package and uses it the most.

Thanks

**Comment by rodmcnew** [comment]
This fix for this was merged in version 2.0.4
